[tool.isort]
profile = "black"
line_length = 88

known_first_party = ["app"]
known_third_party = ["fastapi", "pydantic", "starlette"]

combine_as_imports = true
force_sort_within_sections = true
lines_after_imports = 2
