global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'neurobank-dev'
    environment: 'development'

scrape_configs:
  - job_name: 'neurobank-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
